import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '@repo/ui/global.css';
import { Toaster } from 'sonner';
import { TRPCProvider } from '@/trpc/provider';
import { DialogProvider } from '@/providers/dialog-provider';
import { FloatingProvider } from '@/providers/floating-provider/context';
import { ProfileDrawerProvider } from '@/providers/profile-drawer/provider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <TRPCProvider>
          <Toaster />
          <DialogProvider>
            <FloatingProvider>
              <ProfileDrawerProvider>{children}</ProfileDrawerProvider>
            </FloatingProvider>
          </DialogProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
